[package]
name = "rust-mal"
version = "0.1.0"
authors = ["shinsuke"]

[[bin]]
name = "step1"
path = "src/step1_read_print.rs"

[[bin]]
name = "step2"
path = "src/step2_eval.rs"

[[bin]]
name = "step3"
path = "src/step3_env.rs"

[dependencies]
regex = "0.2"
